### PR TITLE
send email notification for follo-ups after job application

### PR DESCRIPTION
**Pull request by lindaber**
send email notification for follow-ups after job application

You should get an email notification 2 days after you changed "Job Path" to "Send Application", "Recruiters", "Hiring Manager", or "Technical/Cultural" unless the Job Path moved to a higher stage since then.

### CODE REVIEW

**Review by adrienyule — APPROVED** [review]
Awesome!

**Review by SophieUdud — CHANGES_REQUESTED** [review]
Thank you Genji! The feature looks good, however there's some extra metadata files that got into the PR and we wouldn't like to merge them. Could you please delete the following files:
- force-app/main/default/profiles/Custom%3A Marketing Profile.profile-meta.xml
- force-app/main/default/profiles/Custom%3A Sales Profile.profile-meta.xml
- force-app/main/default/profiles/Custom%3A Support Profile.profile-meta.xml
- force-app/main/default/profiles/ReadOnly.profile-meta.xml

It also includes some additional permissions that might cause deployment or packaging errors. Could you please delete the following permissions from the Admin.profile-meta.xml file?
- AIViewInsightObjects
- CreateWorkBadgeDefinition
- FieldServiceAccess
- OmnichannelInventorySync
- SendExternalEmailAvailable
- UseOmnichannelInventoryAPIs
- ViewDeveloperName

Also, the Application__c-Application Layout was modified and the Notes related list deleted. Could you please remove the changes and put back the related list?

Let me know if you have any questions about it. Thank you very much!

**Comment by lindaber** [comment]
Sophie, I'm done with the changes.

**Review by SophieUdud — APPROVED** [review]
Thank you for cleaning up the PR!

**Pull request merged**
